name: Test

on:
    pull_request:
    workflow_call:
jobs:
    test:
        name: Test ${{ matrix.test-name }} on python ${{ matrix.python-version }} on ${{ matrix.os }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                test-name: ["simple", "adasampling"]
                python-version: ["3.8", "3.12"]
                os: ["ubuntu-latest"]
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Run make
              run:
                   cd examples
                   make ${{ matrix.test-name }}
